
###
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
  "userName": "Anita1"
}
###
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
  "userName": "Anita2"
}
###
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
  "userName": "User4"
}



###CREACION TUITE
POST http://localhost:8080/api/tweet
Content-Type: application/json

{
  "userId": 1,
  "tweetText": "Nuevo Tweet ABC 100"


}


###FOLLOWING
POST http://localhost:8080/api/follows
Content-Type: application/json

{
  "userFollowerId": 4,
  "userFolloweeId": 1

}

###TIME LINE
GET http://localhost:8080/api/users/timeline/3
Accept: application/json